import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>My blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="nextjs, myblog, hunting coder" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <script src='example.js'></script> */}

      <nav className={styles.mainnav}>
        <ul>
          <Link href={'/'}><a><li>Home</li></a></Link>
          <Link href={'/about'}><a><li>About</li></a></Link>
          <Link href={'/blog'}><a><li>Blog</li></a></Link>
          <Link href={'/contact'}><a><li>Contact</li></a></Link>
        </ul>
      </nav>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to my Blog
        </h1>

        <p className={styles.description}>
          This blog is for practice and handson experience on Nextjs.
        </p>

        <div className="blogs">
          <h2>Popular blogs:</h2>
          <div className="blogitem">
            <h3>HOw to learn javascript in 2020</h3>
            <p>javascript is a very popular lanuage. It is simple to use.</p>
            <h3>HOw to learn javascript in 2020</h3>
            <p>javascript is a very popular lanuage. It is simple to use.</p>
            <h3>HOw to learn javascript in 2020</h3>
            <p>javascript is a very popular lanuage. It is simple to use.</p>
          </div>

        </div>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
