import Head from 'next/head'
import Link from 'next/link'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <style jsx>{`
          h2{
            font-size:30px;
          }
        `}</style>

      <Head>
        <title>My blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="nextjs, myblog, hunting coder" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <script src='example.js'></script> */}

      <main className={styles.main}>
        <h1 className={styles.title}>
          <span className='mySpan'>Hunting Coder</span>
        </h1>
        <div className={styles.myImgWrap}>
        {/* <Image className={styles.myImg} src="/homeimg.jpg" width={200} height={200}></Image> */}
        <img className={styles.myImg} src="/homeimg.jpg" width={200} height={200} />
        </div>
        

        <p className={styles.description}>
          This blog is for practice and handson experience on Nextjs.
        </p>

        <div className="blogs">
          <h2>Latest blogs:</h2>
          <div className="blogitem">
            <h3>HOw to learn javascript in 2020</h3>
            <p>javascript is a very popular lanuage. It is simple to use.</p>
            <h3>HOw to learn javascript in 2020</h3>
            <p>javascript is a very popular lanuage. It is simple to use.</p>
            <h3>HOw to learn javascript in 2020</h3>
            <p>javascript is a very popular lanuage. It is simple to use.</p>
          </div>

        </div>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}

        </a>
      </footer>
    </div>
  )
}
